version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestNsExternalGitProject
  gitServerName: moaa
  gitUrl: https://github.com/moaaSoftwareAG
  gitUsername: moaaSoftwareAG
  gitBranch: main
